wNAF multiplication for BN256 curve
matter-labs/era-boojum pull request #36
Opened 2024-03-12 20:13 UTC by ZamDimon

# What ❔

This pull request implements multiplication for the BN256 curve.

## Why ❔

Currently, multiplication by a scalar is not implemented for BN256 and therefore one needs to add support for such an operation.

## Checklist

- [x] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [ ] Tests for the changes have been added / updated.
- [ ] Documentation comments have been added / updated.
- [ ] Code has been formatted via `zk fmt` and `zk lint`.

2024-04-04 10:38 UTC, jules requested changes
Everything looks great - as discussed, let's move to the cheaper mul circuit and we should be done here :)

2024-04-04 10:38 UTC, jules commented on src/gadgets/curves/bn256/decomp_table.rs
As discussed, this can be deleted

2024-04-04 10:38 UTC, jules commented on src/gadgets/curves/bn256/naf_abs_div2_table.rs
Can also be deleted I believe

2024-04-04 10:38 UTC, jules commented on src/gadgets/curves/bn256/mul.rs
> +fn convert_to_wnaf<F: SmallField, CS: ConstraintSystem<F>>(
All wNAF functionality can be removed. We keep the GLV decomposition but instead use Alex's fixed-width 4-bit mul circuit found [here](https://github.com/matter-labs/era-zkevm_circuits/blob/v1.4.1/src/ecrecover/new_optimized.rs#L328). Note that the code here deals with potential 129 bit decomposed scalars, whereas bn254 will only occupy max 127 bits. Thus, there should be some extra constraints we can drop as the scalars fit in a smaller size.

2024-04-04 13:25 UTC, ZamDimon commented
Hey @jules, enormous thanks for the review! Updated the wnaf-based scalar multiplication to a fixed-width 4-bit multiplication, as requested, according to implementation [here](https://github.com/matter-labs/era-zkevm_circuits/blob/v1.4.1/src/ecrecover/new_optimized.rs#L328).

After your comment, I am now aware of the extra circuit complexity due to dealing with the potential 129-bit decomposed scalar. Still, I suggest staying with the current implementation since it is well-tested. Then, after we successfully integrate the `ecMul` in the more high-level repositories and make sure it works, we will surely cut off the constraints.

2024-05-22 15:48 UTC, ZamDimon commented
BN254-specific functions will be transferred to [`era-zkevm_circuits`](https://github.com/matter-labs/era-zkevm_circuits/pull/32). For helper gadgets, see #38. Thus, we close this pull request.

2024-05-22 15:48 UTC, closed without merging